# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.1.1"

  on_macos do
    sha256 "943af45c69582ec5947737b38ec7acfb1d570fa87a9cea4aed6ac2f26e7e331e"
    url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "611143e55ed6ad18402b79f3e4dd82c11855ace031da3e4602fb7a39b778dea9"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "05acf5bb993f78588060fd8a8c994e2f726b9859b2c3ab9827e12ae880c9c279"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kin"
  desc "KIN Calendar CLI — talk or type to manage your family calendar"
  homepage "https://github.com/kinassistant/kin-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Voice input requires sox: brew install sox
  EOS
end
