# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.1.23"

  on_macos do
    sha256 "2dad7b8b7d7d7113f51658956094aba7de2af58c74e6b378ede4f6fe34a6a866"
    url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "427cf506930162c6c7fa7b4bb8942062af4b5363ad14cec408268d02345f8081"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a04138a151aef5784f767622a39708624982b57109ea9ef192d1bbfc54cc358"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kin"
  desc "KIN Calendar CLI — talk or type to manage your family calendar"
  homepage "https://github.com/kinassistant/kin-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "sox",
    ]

  binary "kin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Voice input prompts for microphone access on first use.
  EOS
end
