# This file was generated by GoReleaser. DO NOT EDIT.
cask "kin" do
  version "0.1.9"

  on_macos do
    sha256 "c8551b7cd631e91a377c6811e05a1109ad745d5235d9133dd4bb73450b2ec142"
    url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "9b55395565b21c69fe692541b6548c86446a6c21ed30849ccf9d51b85909fa6f"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b4804085cb439e7b5c6a69f61f050484f27718e43c903ccf59344fead90a53d5"
      url "https://github.com/kinassistant/kin-cli/releases/download/v#{version}/kin_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kin"
  desc "KIN Calendar CLI — talk or type to manage your family calendar"
  homepage "https://github.com/kinassistant/kin-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "sox",
    ]

  binary "kin"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kin"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Voice input prompts for microphone access on first use.
  EOS
end
